### ISSUE TITLE
gradle console

### ISSUE THREAD

**Issue by amorenew** [emmasuzuki/EspressoSpoonDemo#1]
sorry for this beginner question
where to execute this ?
$ ./gradlew spoon
 i am using android studio
thanks

**Comment by emmasuzuki** [comment]
Sorry, I did not realize the issue is opened till now.  
In case, you are still having this issue, if you are using Mac or Unix, you should be able to do "./gradlew spoon" under the root directory of this repo when you clone.   If you are using windows, please use gradlew.bat.

**Comment by amorenew** [comment]
thank you very much
