### ISSUE TITLE
Spoon + Coverage

### ISSUE THREAD

**Issue by sregg** [emmasuzuki/EspressoSpoonDemo#2]
Hi,

I was wondering how you can combine the Spoon report and the Jacoco coverage report.
If I run `gradle create${flavor}CoverageReport spoon${flavor}` this will execute the tests twice each time right?
Is there a way to run both but execute the test only once?

Thanks.

**Comment by emmasuzuki** [comment]
That is correct.  I think you can write own gradle task to run test once and produce two reports. However I have not tried yet.
