### ISSUE TITLE
Empty coverage.ec

### ISSUE THREAD

**Issue by youdidut** [emmasuzuki/EspressoSpoonDemo#3]
Hi, Emma!
Thanks for sharing your code with us.
When I run this project on an emulator with ./gradlew createDebugCoverageReport, I got an empty coverage.ec file under build/outputs/code-coverage/connected. 
Have you ever encountered such situation? Do you have any idea why this is happening?

Di

**Comment by emmasuzuki** [comment]
Hi Di,
Yes, I have noticed the behavior since I upgraded Espresso framework to 2.2.  I have not have a chance to research deeper, yet it seems like something around the framework updates.

**Comment by emmasuzuki** [comment]
Jacoco started to work again with Espresso 2.2.1.
