### ISSUE TITLE
[Question] How to run this with openstf?

### ISSUE THREAD

**Issue by santoshgistto** [emmasuzuki/EspressoSpoonDemo#6]

**Comment by emmasuzuki** [comment]
I only used Google Cloud Test Lab for similar needs but never used openstf before but it looks cool.

I found this popular thread in stf.  Check this out.  
https://github.com/openstf/stf/issues/38

**Comment by santoshgistto** [comment]
@emmasuzuki  thanks for you response.
i am going to check this https://github.com/2gis/stf-utils seems it is possible.

**Comment by santoshgistto** [comment]
@emmasuzuki it is possible to connect using stf-utils ,i am able run your sample ,

Thank you :100:
