### ISSUE TITLE
how to get code coverage report

### ISSUE THREAD

**Issue by lionkingshi** [emmasuzuki/EspressoSpoonDemo#7]
run ./gradlew createDebugCoverageReport , 
the command would fail and files are not generated at app/build/reports/coverage/ folder .
why ？

**Comment by emmasuzuki** [comment]
Sorry, this part of ReadMe wasn't clear.  
Jacoco report won't be generated when tests are failing. Yet, in my repo, to demonstrate Spoon's failure report, I purposefully make the testing failure. https://github.com/emmasuzuki/EspressoSpoonDemo/blob/master/app/src/main/java/com/emmasuzuki/espressospoondemo/LoginActivity.java#L81

To obtain jacoco report, you have to uncomment this line.
If tests pass successfully, the folder should be generated.
